sudo: false
language: swift
osx_image: xcode9
cache:
  - bundler
  - cocoapods
matrix:
  include:
    - os: osx
      env:
        - SCHEME="RichString macOS"
        - SDK=macosx
        - DESTINATION="platform=macosx"
        - ACTION=test
    - os: osx
      env:
        - SCHEME="RichString iOS"
        - SDK=iphonesimulator
        - DESTINATION="platform=iOS Simulator,name=iPhone 6,OS=11.0"
        - ACTION=test
    - os: osx
      env:
        - SCHEME="RichString watchOS"
        - SDK=watchsimulator
        - DESTINATION="platform=watchOS Simulator,name=Apple Watch Series 3 - 42mm"
        - ACTION=build
    - os: osx
      env:
        - SCHEME="RichString tvOS"
        - SDK="appletvsimulator"
        - DESTINATION="platform=tvOS Simulator,name=Apple TV 4K"
        - ACTION=test
script:
  - set -o pipefail &&xcodebuild -workspace RichString.xcworkspace -scheme "${SCHEME}" -sdk "${SDK}" -destination "${DESTINATION}" ${ACTION} | xcpretty
  - bundle exec jazzy
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: docs
  on:
    branch: master
